export const FETCH_PROGRAMS_SUCCESS = 'FETCH_PROGRAMS_SUCCESS';
export const FETCH_PROGRAM_ABOUT_SUCCESS = 'FETCH_PROGRAM_ABOUT_SUCCESS';
export const FETCH_PROGRAM_ABOUT_LIST_SUCCESS = 'FETCH_PROGRAM_ABOUT_LIST_SUCCESS';
export const FETCH_ENROLL_PROGRAMS_SUCCESS = 'FETCH_ENROLL_PROGRAMS_SUCCESS';
export const FETCH_ENROLL_PROGRAMS_FAILED = 'FETCH_ENROLL_PROGRAMS_FAILED';
